<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZGZRvG5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZGZRvG5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZGZRvG5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZGZRvG5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZGZRvG5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZGZRvG5',
    'container.build_id' => '266bf872',
    'container.build_time' => 1567078292,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZGZRvG5');
