<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAWNWwK8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAWNWwK8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAWNWwK8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAWNWwK8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAWNWwK8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AWNWwK8',
    'container.build_id' => '979d5227',
    'container.build_time' => 1567876274,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAWNWwK8');
